version: '3'
services:
  db:
    image: mysql:latest
    container_name: new-mysql-db
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: majd
    ports:
      - 3307:3306
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - backendNetwork

  backend:
    depends_on:
      - db
    image: jojo8/dd:latest
    container_name: springbootapp
    restart: on-failure
    ports:
      - 6868:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/spring",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "majd",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backendNetwork

volumes:
  db:
networks:
  backendNetwork: